const router = require('express').Router()
const cors = require('cors')
const bookController = require('../controllers/book')
const authController = require('../controllers/auth')
const verification = require('./verifytoken')
const verificationAdmin = require('./verifytokenAdmin')
router
  .get('/books', bookController.getBooks)
  .get('/book', verification, bookController.getBook)
  .get('/rent', verification, bookController.getrent)
  .get('/genre', bookController.getGenre)
  .get('/', bookController.getBook)
  .delete('/books',verificationAdmin, bookController.deleteBooks)
  .post('/books', bookController.insertBooks)
  .patch('/books', verificationAdmin, bookController.updateBooks)
  .patch('/rent', bookController.Renturn)
  .post('/login', authController.login)
  .post('/rent',verification, bookController.Borrow)
  .post('/register', authController.regiter)
  .get('/token', verification)
module.exports = router
